#!/usr/bin/env bash
set -euo pipefail
REPO="${REPO:-$(gh repo view --json nameWithOwner --jq '.nameWithOwner')}"
create_or_update_label() {
    local name="$1" color="$2" description="$3"
    if gh label list --repo "$REPO" --limit 1000 --json name --jq '.[].name' | grep -qx "$name"; then
        echo "updating label: $name"
        gh label edit "$name" --repo "$REPO" --color "$color" --description "$description"
    else
        echo "creating label: $name"
        gh label create "$name" --repo "$REPO" --color "$color" --description "$description"
    fi
}
echo "syncing labels for $REPO"
create_or_update_label "type:bug" "70cc53" "Something broken or incorrect"
create_or_update_label "type:feature" "70cc53" "New functionality"
create_or_update_label "type:fix" "70cc53" "Bug fix or corrective change"
create_or_update_label "type:task" "70cc53" "General development work"
create_or_update_label "type:refactor" "70cc53" "Internal code restructuring"
create_or_update_label "type:docs" "70cc53" "Documentation work"
create_or_update_label "type:chore" "70cc53" "Maintenance or tooling work"
create_or_update_label "type:test" "70cc53" "Tests or test infrastructure"
create_or_update_label "type:ci" "70cc53" "Continuous integration work"
create_or_update_label "type:build" "70cc53" "Build system work"
create_or_update_label "type:release" "70cc53" "Release, versioning, or publishing work"
create_or_update_label "type:idea" "70cc53" "Future concept or rough improvement"
create_or_update_label "scope:root" "6f42c1" "Workspace root scripts or config"
create_or_update_label "scope:repo" "6f42c1" "Repository-level work"
create_or_update_label "scope:template" "6f42c1" "Template or template-consumer work"
create_or_update_label "scope:scripts" "6f42c1" "Generic tooling or scripts"
create_or_update_label "scope:build-config" "6f42c1" "Build config package"
create_or_update_label "scope:cli-app" "6f42c1" "CLI application package"
create_or_update_label "scope:color" "6f42c1" "Color package"
create_or_update_label "scope:config" "6f42c1" "Shared config package"
create_or_update_label "scope:example-package" "6f42c1" "Example package"
create_or_update_label "scope:logger" "6f42c1" "Logger package"
create_or_update_label "scope:node-utils" "6f42c1" "Node utilities package"
create_or_update_label "scope:playground" "6f42c1" "Playground package or app"
create_or_update_label "scope:scaffold" "6f42c1" "Scaffold package"
create_or_update_label "scope:types" "6f42c1" "Shared types package"
create_or_update_label "scope:utils" "6f42c1" "Utilities package"
create_or_update_label "scope:workspace-tools" "6f42c1" "Workspace tools package"
create_or_update_label "category:build" "0e8a16" "Build system"
create_or_update_label "category:ci" "0e8a16" "Continuous integration"
create_or_update_label "category:deps" "0e8a16" "Dependency management"
create_or_update_label "category:dx" "0e8a16" "Developer experience"
create_or_update_label "category:security" "0e8a16" "Security"
create_or_update_label "category:perf" "0e8a16" "Performance"
create_or_update_label "category:release" "0e8a16" "Release workflow"
create_or_update_label "category:publishing" "0e8a16" "Package publishing"
create_or_update_label "category:docs" "0e8a16" "Documentation generation or publishing"
create_or_update_label "category:testing" "0e8a16" "Testing infrastructure"
create_or_update_label "domain:api" "e99695" "General API work"
create_or_update_label "domain:api-client" "e99695" "API client work"
create_or_update_label "domain:api-server" "e99695" "API server work"
create_or_update_label "domain:build-plan" "e99695" "Build plan generation or normalization"
create_or_update_label "domain:changesets" "e99695" "Changesets workflow"
create_or_update_label "domain:commitlint" "e99695" "Commit message validation"
create_or_update_label "domain:exports" "e99695" "Package exports"
create_or_update_label "domain:formatting" "e99695" "Formatting tools"
create_or_update_label "domain:github-actions" "e99695" "GitHub Actions"
create_or_update_label "domain:github-issues" "e99695" "GitHub issues and project workflow"
create_or_update_label "domain:linting" "e99695" "Linting tools"
create_or_update_label "domain:monorepo" "e99695" "Monorepo structure"
create_or_update_label "domain:package-consumption" "e99695" "External consumer/package testing"
create_or_update_label "domain:smoke-tests" "e99695" "Smoke tests"
create_or_update_label "domain:template-sync" "e99695" "Template/source/consumer sync"
create_or_update_label "domain:typedoc" "e99695" "TypeDoc documentation"
create_or_update_label "domain:string-helpers" "e99695" "String helper utilities"
create_or_update_label "domain:color-tools" "e99695" "Color utilities"
create_or_update_label "sync:template-source" "fbca04" "Change belongs in the template/source repo"
create_or_update_label "sync:template-consumer" "fbca04" "Change belongs in a template consumer repo"
create_or_update_label "sync:needs-sync" "fbca04" "Needs to be synced across repos"
create_or_update_label "sync:synced" "fbca04" "Already synced across repos"
create_or_update_label "sync:manual-port" "fbca04" "Needs manual adaptation while porting"
create_or_update_label "sync:do-not-sync" "fbca04" "Repo-specific; do not sync"
create_or_update_label "priority:low" "d93f0b" "Low priority"
create_or_update_label "priority:normal" "d93f0b" "Normal priority"
create_or_update_label "priority:high" "d93f0b" "High priority"
create_or_update_label "priority:urgent" "d93f0b" "Urgent priority"
echo "done"
